export {default as FAQData} from './FAQ'
export {default as SocialMediaData} from './SocialMedia'
export {PricingData, PricingTabs} from './Pricing'
export {default as InterviewTabs} from './Interview'
export {default as MockInterviewData} from './MockInterview'