const MockInterviewData = [
    {
        title: "Full Stack Developer",
        jobDescription: "We are looking for a Full Stack Developer to produce scalable software solutions. You’ll be part of a cross-functional team that’s responsible for the full software development life cycle, from conception to deployment. As a Full Stack Developer, you should be comfortable around both front-end and back-end coding languages, development frameworks and third-party libraries. You should also be a team player with a knack for visual design and utility. If you’re also familiar with Agile methodologies, we’d like to meet you. Responsibilities: Work with development teams and product managers to ideate software solutions Design client-side and server-side architecture Build the front-end of applications through appealing visual design Develop and manage well-functioning databases and applications Write effective APIs Test software to ensure responsiveness and efficiency Troubleshoot, debug and upgrade software Create security and data protection settings Build features and applications with a mobile responsive design Write technical documentation Work with data scientists and analysts to improve software Requirements and skills Proven experience as a Full Stack Developer or similar role Experience developing desktop and mobile applications Familiarity with common stacks Knowledge of multiple front-end languages and libraries (e.g. HTML/ CSS, JavaScript, XML, jQuery) Knowledge of multiple back-end languages (e.g. C#, Java, Python) and JavaScript frameworks (e.g. Angular, React, Node.js) Familiarity with databases (e.g. MySQL, MongoDB), web servers (e.g. Apache) and UI/UX design Excellent communication and teamwork skills Great attention to detail Organizational skills An analytical mind",
    },
    {
        title: "Front End Developer",
        jobDescription: "We are looking for a qualified Front-end developer to join our IT team. You will be responsible for building the ‘client-side’ of our web applications. You should be able to translate our company and customer needs into functional and appealing interactive applications. If you’re interested in creating a user-friendly environment by writing code and moving forward in your career, then this job is for you. We expect you to be a tech-savvy professional, who is curious about new digital technologies and aspires to combine usability with visual design. Ultimately, you should be able to create a functional and attractive digital environment for our company, ensuring great user experience. Responsibilities Use markup languages like HTML to create user-friendly web pages Maintain and improve website Optimize applications for maximum speed Design mobile-based features Collaborate with back-end developers and web designers to improve usability Get feedback from, and build solutions for, users and customers Write functional requirement documents and guides Create quality mockups and prototypes Help back-end developers with coding and troubleshooting Ensure high quality graphic standards and brand consistency Stay up-to-date on emerging technologies Requirements and skills Proven work experience as a Front-end developer Hands on experience with markup languages Experience with JavaScript, CSS and jQuery Familiarity with browser testing and debugging In-depth understanding of the entire web development process (design, development and deployment) Understanding of layout aesthetics Knowledge of SEO principles Familiarity with software like Adobe Suite, Photoshop and content management systems An ability to perform well in a fast-paced environment Excellent analytical and multitasking skills",
    },
    {
        title: "Business Development Manager",
        jobDescription: "prospective clients Promote the company’s products/services addressing or predicting clients’ objectives Prepare sales contracts ensuring adherence to law-established rules and guidelines Keep records of sales, revenue, invoices etc. Provide trustworthy feedback and after-sales support Build long-term relationships with new and existing customers Develop entry level staff into valuable salespeople Requirements and skills Proven working experience as a business development manager, sales executive or a relevant role Proven sales track record Experience in customer support is a plus Proficiency in MS Office and CRM software (e.g. Salesforce) Proficiency in English Market knowledge Communication and negotiation skills Ability to build rapport Time management and planning skills",
    },
    {
        title: "Lead Product Designer",
        jobDescription: "web apps, efficiently and beautifully. Collaborate with product peers and leadership to realize short and long term product vision. Further operationalize the design process with an eye towards growth and scale. Approach design challenges holistically, considering all parts of the experience including UI/UX, business, and legal requirements. Iterate on existing products and features to ensure that we are delivering simple industry-leading user experience Work with Product and Engineering to build intuitive, elegant solutions. Partner with product to conduct research to help inform the customer experience Deeply understand the needs of a diverse user base consisting of consumers, merchants, and business partners. Drive alignment and decisions by working collaboratively with and presenting designs to leadership and cross functional teams including product, engineering, customer success, and marketing. Mentor junior designers Requirements: 5+ years of experience designing and shipping products and features from inception to launch in a fast paced environment Strong knowledge of best practices in UI / UX and information architecture across iOS, Android and responsive web Ability to manage multiple priorities, adhere to deadlines, and iterate quickly in a highly collaborative, fast-paced environment Lo-fi & hi-fi prototyping skills Strong interaction and visual design skills. High proficiency in Figma Ability to reduce complex problems down to flexible, intuitive patterns and solutions. Ability to communicate design rationale and decisions with product, engineering, marketing and leadership Experience working with data to inform design decisions Experience hiring, managing or mentoring designers Knowledge of common UI frameworks like React Native / Web Exceptional written & verbal communication ability",
    },
];

export default MockInterviewData;