export {default as Hero} from './Hero';
export {default as Features} from './Features';
export {default as Insights} from './Insights';
export {default as Jobs} from './Jobs';
export {default as Interview} from './Interview';
export {default as Working} from './Working';
export {default as Pricing} from './Pricing';
export {default as FAQ} from './FAQ';
export {default as Footer} from './Footer'; 